package com.yhaguy.util.migracion.cinpal;

import com.coreweb.domain.Tipo;
import com.yhaguy.domain.*;

import java.util.*;

public class Modelo {

	static String[][] modelos = {{"Agrale","AGR","1600D / 1800D / 4500D / 5000DE","Vehículo"},
			{"Agrale","AGR","240V (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","7000DX / TX1200/TX1600/TX1800","Vehículo"},
			{"Agrale","AGR","7500/8500/MA 7.5/ MA 8.5","Vehículo"},
			{"Agrale","AGR","AGRALE 13000 6X2","Vehículo"},
			{"Agrale","AGR","Agrale 9200","Vehículo"},
			{"Agrale","AGR","Agrale Furgovan 8000","Vehículo"},
			{"Agrale","AGR","Agrale MA 12 TCA","Vehículo"},
			{"Agrale","AGR","Agrale MA 8.5 TCA","Vehículo"},
			{"Agrale","AGR","Agrale MA 9.2 TCA","Vehículo"},
			{"Agrale","AGR","Agrale Volare A8","Vehículo"},
			{"Agrale","AGR","Agrale Volare A8 - RHD Africa","Vehículo"},
			{"Agrale","AGR","Agrale Volare W8 - Eletronico","Vehículo"},
			{"Agrale","AGR","CL-2615C","Caja de Cambio"},
			{"Agrale","AGR","FS-2305","Caja de Cambio"},
			{"Agrale","AGR","FS-4205 (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","FS-4205A (AGRALE)","Caja de Cambio"},
			{"Agrale","AGR","FS-4405C","Caja de Cambio"},
			{"Agrale","AGR","FS-5205A (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","FS-5406A","Caja de Cambio"},
			{"Agrale","AGR","FS-6406A/B","Caja de Cambio"},
			{"Agrale","AGR","FSB-5305D (AGRALE)","Caja de Cambio"},
			{"Agrale","AGR","FSB-5406A (AGRALE)","Vehículo"},
			{"Agrale","AGR","FSB-6406A (AGRALE)","Caja de Cambio"},
			{"Agrale","AGR","FSB-6406B (AGRALE)","Caja de Cambio"},
			{"Agrale","AGR","FSO-4305 (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","FSO-4305 A/B/C (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","FSO-4305A (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","FSO-4305C","Caja de Cambio"},
			{"Agrale","AGR","FSO-4405 (Agrale)","Caja de Cambio"},
			{"Agrale","AGR","FSO-4405C","Caja de Cambio"},
			{"Agrale","AGR","FSO-6406A","Caja de Cambio"},
			{"Agrale","AGR","FSO-8406A","Caja de Cambio"},
			{"Agrale","AGR","MA 12.0 ÔNIBUS","Vehículo"},
			{"Agrale","AGR","MA 7.5 T","Vehículo"},
			{"Agrale","AGR","MA 9.2TCA","Vehículo"},
			{"Agrale","AGR","MA12 TCA","Vehículo"},
			{"Agrale","AGR","MA8.5 TCA","Vehículo"},
			{"Agrale","AGR","MT 12","Vehículo"},
			{"Agrale","AGR","Ônibus-MA12 TCA/MT12","Vehículo"},
			{"Agrale","AGR","TX1200","Vehículo"},
			{"Agrale","AGR","TX1600","Vehículo"},
			{"Agrale","AGR","VOLARE A8","Vehículo"},
			{"Agrale","AGR","VOLARE W8 - Eletronico","Vehículo"},
			{"Alfa Metais","AMT","FSO-4305 (Alfa Metais)","Caja de Cambio"},
			{"Alfa Metais","AMT","PUMA 7900 CB","Vehículo"},
			{"Cummins","REF","6BD 5.9","Motor"},
			{"Cummins","REF","Série 4B 3.9","Motor"},
			{"Cummins","REF","Série 6B","Motor"},
			{"Cummins","REF","Série 6B 5.9","Motor"},
			{"Cummins","REF","Série 6C","Motor"},
			{"Cummins","REF","Série 6C 8.3","Motor"},
			{"Cummins","REF","Série ISB","Motor"},
			{"Cummins","REF","Série ISB Eletrônico","Motor"},
			{"Cummins","REF","Série ISC","Motor"},
			{"Cummins","REF","Série ISC Eletrônico","Motor"},
			{"Ford","FRD","1618","Vehículo"},
			{"Ford","FRD","1621","Vehículo"},
			{"Ford","FRD","240F","Caja de Cambio"},
			{"Ford","FRD","240FS","Caja de Cambio"},
			{"Ford","FRD","240V (Ford)","Caja de Cambio"},
			{"Ford","FRD","260V","Caja de Cambio"},
			{"Ford","FRD","280V","Caja de Cambio"},
			{"Ford","FRD","280VH","Caja de Cambio"},
			{"Ford","FRD","390V","Caja de Cambio"},
			{"Ford","FRD","BUS 1618","Vehículo"},
			{"Ford","FRD","BUS 1621","Vehículo"},
			{"Ford","FRD","CARGO 1113","Vehículo"},
			{"Ford","FRD","CARGO 1113 FTO","Vehículo"},
			{"Ford","FRD","CARGO 1114","Vehículo"},
			{"Ford","FRD","CARGO 1117","Vehículo"},
			{"Ford","FRD","CARGO 1117 FTO","Vehículo"},
			{"Ford","FRD","CARGO 1212 FTO","Vehículo"},
			{"Ford","FRD","CARGO 1215","Vehículo"},
			{"Ford","FRD","CARGO 1313","Vehículo"},
			{"Ford","FRD","CARGO 1313 MWM","Vehículo"},
			{"Ford","FRD","CARGO 1313FTO","Vehículo"},
			{"Ford","FRD","CARGO 1314","Vehículo"},
			{"Ford","FRD","CARGO 1314 MWM","Vehículo"},
			{"Ford","FRD","CARGO 1317","Vehículo"},
			{"Ford","FRD","CARGO 1317 FTO","Vehículo"},
			{"Ford","FRD","CARGO 1317A","Vehículo"},
			{"Ford","FRD","CARGO 1317E","Vehículo"},
			{"Ford","FRD","CARGO 1414","Vehículo"},
			{"Ford","FRD","CARGO 1415","Vehículo"},
			{"Ford","FRD","CARGO 1416","Vehículo"},
			{"Ford","FRD","CARGO 1418","Vehículo"},
			{"Ford","FRD","CARGO 1418/ 1618/ 2218","Vehículo"},
			{"Ford","FRD","CARGO 1419","Vehículo"},
			{"Ford","FRD","CARGO 1421","Vehículo"},
			{"Ford","FRD","CARGO 1422","Vehículo"},
			{"Ford","FRD","CARGO 1514","Vehículo"},
			{"Ford","FRD","CARGO 1514 (FDT)","Vehículo"},
			{"Ford","FRD","CARGO 1514FTD","Vehículo"},
			{"Ford","FRD","CARGO 1516","Vehículo"},
			{"Ford","FRD","CARGO 1517","Vehículo"},
			{"Ford","FRD","CARGO 1517E","Vehículo"},
			{"Ford","FRD","CARGO 1519","Vehículo"},
			{"Ford","FRD","CARGO 1521","Vehículo"},
			{"Ford","FRD","CARGO 1615","Vehículo"},
			{"Ford","FRD","CARGO 1617","Vehículo"},
			{"Ford","FRD","CARGO 1617-CB","Vehículo"},
			{"Ford","FRD","CARGO 1617C","Vehículo"},
			{"Ford","FRD","CARGO 1618","Vehículo"},
			{"Ford","FRD","CARGO 1619","Vehículo"},
			{"Ford","FRD","CARGO 1621","Vehículo"},
			{"Ford","FRD","CARGO 1622","Vehículo"},
			{"Ford","FRD","CARGO 1716","Vehículo"},
			{"Ford","FRD","CARGO 1717","Vehículo"},
			{"Ford","FRD","CARGO 1717E","Vehículo"},
			{"Ford","FRD","CARGO 1721","Vehículo"},
			{"Ford","FRD","CARGO 1721 CKD","Caja de Cambio"},
			{"Ford","FRD","CARGO 1721 CKD","Vehículo"},
			{"Ford","FRD","CARGO 1722","Vehículo"},
			{"Ford","FRD","CARGO 1722-B","Vehículo"},
			{"Ford","FRD","CARGO 1722-E","Caja de Cambio"},
			{"Ford","FRD","CARGO 1722A","Vehículo"},
			{"Ford","FRD","CARGO 1728-E","Vehículo"},
			{"Ford","FRD","CARGO 1730","Vehículo"},
			{"Ford","FRD","CARGO 1731","Vehículo"},
			{"Ford","FRD","Cargo 1932/33/2632/3132/33","Vehículo"},
			{"Ford","FRD","CARGO 2217","Vehículo"},
			{"Ford","FRD","CARGO 2218","Vehículo"},
			{"Ford","FRD","CARGO 2319","Vehículo"},
			{"Ford","FRD","CARGO 2321","Vehículo"},
			{"Ford","FRD","CARGO 2322","Vehículo"},
			{"Ford","FRD","CARGO 2322 CB","Vehículo"},
			{"Ford","FRD","CARGO 2422","Vehículo"},
			{"Ford","FRD","CARGO 2422 E","Vehículo"},
			{"Ford","FRD","CARGO 2425","Vehículo"},
			{"Ford","FRD","CARGO 2428 E","Vehículo"},
			{"Ford","FRD","CARGO 2622","Vehículo"},
			{"Ford","FRD","CARGO 2622E","Vehículo"},
			{"Ford","FRD","CARGO 2626","Vehículo"},
			{"Ford","FRD","CARGO 2628E","Vehículo"},
			{"Ford","FRD","CARGO 2629","Vehículo"},
			{"Ford","FRD","CARGO 2630","Vehículo"},
			{"Ford","FRD","CARGO 2631","Vehículo"},
			{"Ford","FRD","CARGO 2831","Vehículo"},
			{"Ford","FRD","CARGO 2932E","Vehículo"},
			{"Ford","FRD","CARGO 3021","Vehículo"},
			{"Ford","FRD","CARGO 3222-A","Caja de Cambio"},
			{"Ford","FRD","CARGO 3222 E 2005/","Caja de Cambio"},
			{"Ford","FRD","CARGO 3222E","Vehículo"},
			{"Ford","FRD","CARGO 3224","Vehículo"},
			{"Ford","FRD","CARGO 3224-CN","Vehículo"},
			{"Ford","FRD","CARGO 3228-E","Vehículo"},
			{"Ford","FRD","CARGO 3530","Vehículo"},
			{"Ford","FRD","CARGO 4030","Vehículo"},
			{"Ford","FRD","CARGO 4031","Vehículo"},
			{"Ford","FRD","CARGO 4331","Vehículo"},
			{"Ford","FRD","CARGO 4331S","Vehículo"},
			{"Ford","FRD","CARGO 4432E","Vehículo"},
			{"Ford","FRD","CARGO 5032E","Vehículo"},
			{"Ford","FRD","CARGO 814","Vehículo"},
			{"Ford","FRD","CARGO 815","Vehículo"},
			{"Ford","FRD","CARGO 815E","Motor"},
			{"Ford","FRD","CARGO 815E ARG/CHILE","Vehículo"},
			{"Ford","FRD","CARGO 815E BRA/URU/PARAG.","Vehículo"},
			{"Ford","FRD","CARGO 815E VENEZ/COMBIA","Vehículo"},
			{"Ford","FRD","CARGO 815S","Motor"},
			{"Ford","FRD","CARGO 816","Vehículo"},
			{"Ford","FRD","CARGO 816 BRA/PAR/URU","Vehículo"},
			{"Ford","FRD","CARGO 915","Motor"},
			{"Ford","FRD","CARGO 915E","Vehículo"},
			{"Ford","FRD","CARGO 915E ARG/CHILE","Vehículo"},
			{"Ford","FRD","CARGO 915E BRA/URUG/ PARAG.","Vehículo"},
			{"Ford","FRD","CARGO 915E VENEZ/COMBIA","Vehículo"},
			{"Ford","FRD","CARGO 916","Vehículo"},
			{"Ford","FRD","CARGO 916 CHILE/ARG","Vehículo"},
			{"Ford","FRD","CARGO 916 VEN/COL","Vehículo"},
			{"Ford","FRD","CARGO 916 BRA/PAR/URU","Vehículo"},
			{"Ford","FRD","CL-2215","Caja de Cambio"},
			{"Ford","FRD","CL-2615B","Caja de Cambio"},
			{"Ford","FRD","CL-450 (Ford)","Caja de Cambio"},
			{"Ford","FRD","CL-550","Caja de Cambio"},
			{"Ford","FRD","F-100 TURBO","Vehículo"},
			{"Ford","FRD","F-1000","Vehículo"},
			{"Ford","FRD","F-1000 Turbo","Vehículo"},
			{"Ford","FRD","F-1000NA","Vehículo"},
			{"Ford","FRD","F-11000","Vehículo"},
			{"Ford","FRD","F-12000","Vehículo"},
			{"Ford","FRD","F-14000","Vehículo"},
			{"Ford","FRD","F-16000","Vehículo"},
			{"Ford","FRD","F-2000","Vehículo"},
			{"Ford","FRD","F-22000","Vehículo"},
			{"Ford","FRD","F-250","Vehículo"},
			{"Ford","FRD","F-350","Vehículo"},
			{"Ford","FRD","F-400","Vehículo"},
			{"Ford","FRD","F-4000","Vehículo"},
			{"Ford","FRD","F-4000 Turbo C/ Freio Estac.","Vehículo"},
			{"Ford","FRD","F-600","Vehículo"},
			{"Ford","FRD","F14000 2001/","Vehículo"},
			{"Ford","FRD","F14000 / F16000","Vehículo"},
			{"Ford","FRD","FS-2305","Caja de Cambio"},
			{"Ford","FRD","FS-4005 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-4005A/B (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-4005A/B (GM)","Caja de Cambio"},
			{"Ford","FRD","FS-4205 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-4205A (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-5005 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-5005A (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-5005A/C (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-5106 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-5205 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-5205A (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-5205C (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-5306 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-5406","Caja de Cambio"},
			{"Ford","FRD","FS-5406A","Caja de Cambio"},
			{"Ford","FRD","FS-6005 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-6005B","Caja de Cambio"},
			{"Ford","FRD","FS-6105","Caja de Cambio"},
			{"Ford","FRD","FS-6205 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-6205B","Caja de Cambio"},
			{"Ford","FRD","FS-6206 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-6306 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FS-6306A (FORD)","Caja de Cambio"},
			{"Ford","FRD","FS-6406A","Caja de Cambio"},
			{"Ford","FRD","FS-6406A/B","Caja de Cambio"},
			{"Ford","FRD","FSB-5305 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FSB-5305D (FORD)","Caja de Cambio"},
			{"Ford","FRD","FSB-6406A (FORD)","Caja de Cambio"},
			{"Ford","FRD","FSB-6406B (FORD)","Caja de Cambio"},
			{"Ford","FRD","FSO-2405F","Caja de Cambio"},
			{"Ford","FRD","FSO-4305 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FSO-4305 A/B/C (Ford)","Caja de Cambio"},
			{"Ford","FRD","FSO-4305A (FORD)","Caja de Cambio"},
			{"Ford","FRD","FSO-4305B (FORD)","Caja de Cambio"},
			{"Ford","FRD","FSO-4305C (Ford)","Caja de Cambio"},
			{"Ford","FRD","FSO-4405 (Ford)","Caja de Cambio"},
			{"Ford","FRD","FSO-4405C","Caja de Cambio"},
			{"Ford","FRD","FSO-6406A","Caja de Cambio"},
			{"Ford","FRD","FSO-8406A","Caja de Cambio"},
			{"Ford","FRD","MD/RD 23-145","Vehículo"},
			{"Ford","FRD","MS-23-155 / RS-23-155","Eje"},
			{"Ford","FRD","ONIBUS 1618 (ano 1996 / )","Vehículo"},
			{"Ford","FRD","Ônibus C-1622/3530","Vehículo"},
			{"Ford","FRD","RS-23-230 (Ford)","Vehículo"},
			{"Ford","FRD","RS-23-240 (Ford)","Eje"},
			{"Ford","FRD","RT 1170B","Caja de Cambio"},
			{"Ford","FRD","RT 11710","Caja de Cambio"},
			{"Ford","FRD","RT 7608LL","Caja de Cambio"},
			{"Ford","FRD","RT 8608LL","Caja de Cambio"},
			{"Ford","FRD","RT 8609","Caja de Cambio"},
			{"Ford","FRD","RT 8908LL","Vehículo"},
			{"Ford","FRD","RTL 012913","Caja de Cambio"},
			{"Ford","FRD","RTL 014918","Caja de Cambio"},
			{"Ford","FRD","RTLO 12913A","Caja de Cambio"},
			{"Ford","FRD","RTLO 14918B","Caja de Cambio"},
			{"Ford","FRD","S5-42 (Ford)","Caja de Cambio"},
			{"Ford","FRD","S5-420 (FORD)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","240FS","Caja de Cambio"},
			{"GMC/Chevrolet","GM","240V (GM)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","260V","Caja de Cambio"},
			{"GMC/Chevrolet","GM","280V","Caja de Cambio"},
			{"GMC/Chevrolet","GM","A-11000","Vehículo"},
			{"GMC/Chevrolet","GM","A-12000","Vehículo"},
			{"GMC/Chevrolet","GM","A-13000","Vehículo"},
			{"GMC/Chevrolet","GM","A-19000","Vehículo"},
			{"GMC/Chevrolet","GM","A-20","Vehículo"},
			{"GMC/Chevrolet","GM","A-21000","Vehículo"},
			{"GMC/Chevrolet","GM","A-22000","Vehículo"},
			{"GMC/Chevrolet","GM","A-40","Vehículo"},
			{"GMC/Chevrolet","GM","A-60","Vehículo"},
			{"GMC/Chevrolet","GM","A-70","Vehículo"},
			{"GMC/Chevrolet","GM","C-11000","Vehículo"},
			{"GMC/Chevrolet","GM","C-12000","Vehículo"},
			{"GMC/Chevrolet","GM","C-13000","Vehículo"},
			{"GMC/Chevrolet","GM","C-19000","Vehículo"},
			{"GMC/Chevrolet","GM","C-20","Vehículo"},
			{"GMC/Chevrolet","GM","C-21000","Vehículo"},
			{"GMC/Chevrolet","GM","C-22000","Vehículo"},
			{"GMC/Chevrolet","GM","C-40","Vehículo"},
			{"GMC/Chevrolet","GM","C-60","Vehículo"},
			{"GMC/Chevrolet","GM","Chevrolet Brasil 60","Vehículo"},
			{"GMC/Chevrolet","GM","Chevrolet Brasil 78","Vehículo"},
			{"GMC/Chevrolet","GM","CL-2205","Caja de Cambio"},
			{"GMC/Chevrolet","GM","CL-2615B","Caja de Cambio"},
			{"GMC/Chevrolet","GM","CL-450 (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","D-10","Vehículo"},
			{"GMC/Chevrolet","GM","D-11000","Vehículo"},
			{"GMC/Chevrolet","GM","D-12000","Vehículo"},
			{"GMC/Chevrolet","GM","D-13000","Vehículo"},
			{"GMC/Chevrolet","GM","D-1400","Vehículo"},
			{"GMC/Chevrolet","GM","D-14000","Vehículo"},
			{"GMC/Chevrolet","GM","D-19000","Vehículo"},
			{"GMC/Chevrolet","GM","D-20","Vehículo"},
			{"GMC/Chevrolet","GM","D-20NA","Vehículo"},
			{"GMC/Chevrolet","GM","D-21000","Vehículo"},
			{"GMC/Chevrolet","GM","D-22000","Vehículo"},
			{"GMC/Chevrolet","GM","D-40","Vehículo"},
			{"GMC/Chevrolet","GM","D-400","Vehículo"},
			{"GMC/Chevrolet","GM","D-60","Vehículo"},
			{"GMC/Chevrolet","GM","D-70","Vehículo"},
			{"GMC/Chevrolet","GM","D-700","Vehículo"},
			{"GMC/Chevrolet","GM","D-80","Vehículo"},
			{"GMC/Chevrolet","GM","D-900","Vehículo"},
			{"GMC/Chevrolet","GM","E-11","Vehículo"},
			{"GMC/Chevrolet","GM","E-13","Vehículo"},
			{"GMC/Chevrolet","GM","E-21","Vehículo"},
			{"GMC/Chevrolet","GM","F-13000","Vehículo"},
			{"GMC/Chevrolet","GM","F-19000","Vehículo"},
			{"GMC/Chevrolet","GM","F-21000","Vehículo"},
			{"GMC/Chevrolet","GM","F-60","Vehículo"},
			{"GMC/Chevrolet","GM","F-600","Vehículo"},
			{"GMC/Chevrolet","GM","F-700","Vehículo"},
			{"GMC/Chevrolet","GM","F-7000","Vehículo"},
			{"GMC/Chevrolet","GM","F-750","Vehículo"},
			{"GMC/Chevrolet","GM","F-8000","Vehículo"},
			{"GMC/Chevrolet","GM","F-8500","Vehículo"},
			{"GMC/Chevrolet","GM","FS-2305","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-4005 (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-4205 (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-4205A (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-5005A/C (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-5205 (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-5205A (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-5205C (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-5306 (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-6306 (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FS-6306A (GM)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSB-5305D (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSB-6406 (GM)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSO-1305","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSO-2405E","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSO-4305 (GM)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSO-4305 A/B/C (GMC)","Caja de Cambio"},
			{"GMC/Chevrolet","GM","FSO-4305B","Caja de Cambio"},
			{"GMC/Chevrolet","GM","GMC 12-170","Vehículo"},
			{"GMC/Chevrolet","GM","GMC 12-170 HD","Vehículo"},
			{"GMC/Chevrolet","GM","GMC 14-190","Vehículo"},
			{"GMC/Chevrolet","GM","GMC 15-190","Vehículo"},
			{"GMC/Chevrolet","GM","GMC 16-220","Vehículo"},
			{"GMC/Chevrolet","GM","GMC 6-150","Vehículo"},
			{"GMC/Chevrolet","GM","MICROÔNIBUS","Vehículo"},
			{"GMC/Chevrolet","GM","Ônibus Colombia","Vehículo"},
			{"GMC/Chevrolet","GM","RS-23-230 (GM)","Vehículo"},
			{"GMC/Chevrolet","GM","RS-23-240 (GM)","Eje"},
			{"GMC/Chevrolet","GM","S5-420 (GM)","Vehículo"},
			{"GMC/Chevrolet","GM","Silverado","Vehículo"},
			{"International","Int","4700","Caja de Cambio"},
			{"International","Int","4900 4x2","Vehículo"},
			{"International","Int","9800 4x2","Vehículo"},
			{"International","Int","FS-5306","Caja de Cambio"},
			{"International","Int","FS-5306 (International)","Caja de Cambio"},
			{"International","Int","FS-6306 (INTERNATIONAL)","Caja de Cambio"},
			{"International","Int","FS-6306A (INTERNACIONAL)","Caja de Cambio"},
			{"International","Int","FSB-5305D (Internacional)","Caja de Cambio"},
			{"International","Int","RT 7608LL","Vehículo"},
			{"International","Int","RTLOF 14913A","Caja de Cambio"},
			{"International","Int","RTLOF 16918B","Caja de Cambio"},
			{"International","Int","RTLOF 18913A","Caja de Cambio"},
			{"International","Int","S9800 6x4","Vehículo"},
			{"Iveco/Fiat","FIA","15DT","Vehículo"},
			{"Iveco/Fiat","FIA","16S-1300","Caja de Cambio"},
			{"Iveco/Fiat","FIA","16S-1300 (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","16S-1300 (IVECO)","Vehículo"},
			{"Iveco/Fiat","FIA","16S-1600 (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","16S-1650 ( IVECO )","Caja de Cambio"},
			{"Iveco/Fiat","FIA","16S-1685","Caja de Cambio"},
			{"Iveco/Fiat","FIA","16S-221","Caja de Cambio"},
			{"Iveco/Fiat","FIA","16S-221 / 16S-2320 / 16S-2280T","Vehículo"},
			{"Iveco/Fiat","FIA","16S-221/2521/2320/2321/","Caja de Cambio"},
			{"Iveco/Fiat","FIA","CC170","Vehículo"},
			{"Iveco/Fiat","FIA","CC220","Vehículo"},
			{"Iveco/Fiat","FIA","Daily S-2007 7.0 Ton","Caja de Cambio"},
			{"Iveco/Fiat","FIA","Eurocargo 120E15","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 140E 18","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 160E21","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 160E23","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 170E22 2005/06 6X2","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 230E24","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 260 E 25","Vehículo"},
			{"Iveco/Fiat","FIA","Eurocargo 6x2","Vehículo"},
			{"Iveco/Fiat","FIA","Eurotech 450E37","Vehículo"},
			{"Iveco/Fiat","FIA","Eurotech E37","Vehículo"},
			{"Iveco/Fiat","FIA","Eurotrakker","Vehículo"},
			{"Iveco/Fiat","FIA","FIAT-120","Vehículo"},
			{"Iveco/Fiat","FIA","FIAT-130","Vehículo"},
			{"Iveco/Fiat","FIA","FIAT-140","Vehículo"},
			{"Iveco/Fiat","FIA","FIAT-70","Vehículo"},
			{"Iveco/Fiat","FIA","FIAT-80","Vehículo"},
			{"Iveco/Fiat","FIA","Fiat 180","Vehículo"},
			{"Iveco/Fiat","FIA","FIAT 190 Brasil","Vehículo"},
			{"Iveco/Fiat","FIA","FNM D-9500","Vehículo"},
			{"Iveco/Fiat","FIA","FS-4205 (Iveco)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-4205A (FORD)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5005 (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5005C","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5205 (Iveco)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5205A (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5205C (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5306 (Iveco)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-5406A","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-6305 A/B","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-6305B","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-6306A (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FS-6406A/B","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSB-5305D (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSB-5406A (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSB-6406A (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSB-6406B (IVECO)","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSO-2405E","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSO-4405B","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSO-6406A","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FSO-8406A","Caja de Cambio"},
			{"Iveco/Fiat","FIA","FT 7000","Vehículo"},
			{"Iveco/Fiat","FIA","FT 8000","Vehículo"},
			{"Iveco/Fiat","FIA","IVECO 150","Vehículo"},
			{"Iveco/Fiat","FIA","Iveco 150T","Vehículo"},
			{"Iveco/Fiat","FIA","IVECO 190/619/697/697T","Vehículo"},
			{"Iveco/Fiat","FIA","IVECO EUROCARGO 140E18","Vehículo"},
			{"Iveco/Fiat","FIA","Iveco Eurocargo 6x2","Caja de Cambio"},
			{"Iveco/Fiat","FIA","IVECO ÔNIBUS CC 118E 20","Vehículo"},
			{"Iveco/Fiat","FIA","IVECO ÔNIBUS CC 170E 220","Vehículo"},
			{"Iveco/Fiat","FIA","Ônibus-CC 170E220","Vehículo"},
			{"Iveco/Fiat","FIA","Power Star 450","Vehículo"},
			{"Iveco/Fiat","FIA","Power Star 450E37T","Vehículo"},
			{"Iveco/Fiat","FIA","RP MD 23165 / 23160","Vehículo"},
			{"Iveco/Fiat","FIA","RS-23-240 (Iveco)","Vehículo"},
			{"Iveco/Fiat","FIA","RS MS 13185 / RS MR 23160","Vehículo"},
			{"Iveco/Fiat","FIA","RT 9509B e C","Caja de Cambio"},
			{"Iveco/Fiat","FIA","RT 9513","Caja de Cambio"},
			{"Iveco/Fiat","FIA","STRALIS","Vehículo"},
			{"MAN","MAN","19-400/25-400/26-400/31-400","Vehículo"},
			{"MAN","MAN","TGX","Vehículo"},
			{"Maxion","MAX","Maxion Aspirado S-4","Motor"},
			{"Maxion","MAX","Maxion S4T Plus","Motor"},
			{"Maxion","MAX","S4T","Motor"},
			{"Mercedes Benz","MB","","Eje"},
			{"Mercedes Benz","MB","1111","Vehículo"},
			{"Mercedes Benz","MB","1113","Vehículo"},
			{"Mercedes Benz","MB","1114","Vehículo"},
			{"Mercedes Benz","MB","1116","Vehículo"},
			{"Mercedes Benz","MB","1118","Vehículo"},
			{"Mercedes Benz","MB","1214","Vehículo"},
			{"Mercedes Benz","MB","1215 C","Vehículo"},
			{"Mercedes Benz","MB","1218","Vehículo"},
			{"Mercedes Benz","MB","1224","Vehículo"},
			{"Mercedes Benz","MB","1313","Vehículo"},
			{"Mercedes Benz","MB","1314","Vehículo"},
			{"Mercedes Benz","MB","1315","Vehículo"},
			{"Mercedes Benz","MB","1316","Vehículo"},
			{"Mercedes Benz","MB","1317","Vehículo"},
			{"Mercedes Benz","MB","1318","Vehículo"},
			{"Mercedes Benz","MB","1414","Vehículo"},
			{"Mercedes Benz","MB","1416","Vehículo"},
			{"Mercedes Benz","MB","1417","Vehículo"},
			{"Mercedes Benz","MB","1417E","Vehículo"},
			{"Mercedes Benz","MB","1418","Vehículo"},
			{"Mercedes Benz","MB","1419","Vehículo"},
			{"Mercedes Benz","MB","1420","Vehículo"},
			{"Mercedes Benz","MB","1421","Vehículo"},
			{"Mercedes Benz","MB","1513","Vehículo"},
			{"Mercedes Benz","MB","1514","Vehículo"},
			{"Mercedes Benz","MB","1516","Vehículo"},
			{"Mercedes Benz","MB","1517","Vehículo"},
			{"Mercedes Benz","MB","1518","Vehículo"},
			{"Mercedes Benz","MB","1519","Vehículo"},
			{"Mercedes Benz","MB","1520","Vehículo"},
			{"Mercedes Benz","MB","1521","Vehículo"},
			{"Mercedes Benz","MB","1524","Vehículo"},
			{"Mercedes Benz","MB","1525","Vehículo"},
			{"Mercedes Benz","MB","1614","Vehículo"},
			{"Mercedes Benz","MB","1615","Vehículo"},
			{"Mercedes Benz","MB","1617","Vehículo"},
			{"Mercedes Benz","MB","1618","Vehículo"},
			{"Mercedes Benz","MB","1620","Vehículo"},
			{"Mercedes Benz","MB","1621","Vehículo"},
			{"Mercedes Benz","MB","1622","Vehículo"},
			{"Mercedes Benz","MB","1625","Vehículo"},
			{"Mercedes Benz","MB","1628","Vehículo"},
			{"Mercedes Benz","MB","1628","Motor"},
			{"Mercedes Benz","MB","1630","Vehículo"},
			{"Mercedes Benz","MB","1632","Vehículo"},
			{"Mercedes Benz","MB","1633","Vehículo"},
			{"Mercedes Benz","MB","1634","Vehículo"},
			{"Mercedes Benz","MB","1635","Vehículo"},
			{"Mercedes Benz","MB","1636","Vehículo"},
			{"Mercedes Benz","MB","16S-130 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","16S-1300 (MBB)","Caja de Cambio"},
			{"Mercedes Benz","MB","16S-160 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","16S-1600","Vehículo"},
			{"Mercedes Benz","MB","16S-1650 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","16S-1685-TO","Vehículo"},
			{"Mercedes Benz","MB","16S-190 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","16S-1900 (MB)","Vehículo"},
			{"Mercedes Benz","MB","16S-221","Caja de Cambio"},
			{"Mercedes Benz","MB","16S-2220TD-TO / 16S-2521-TO","Vehículo"},
			{"Mercedes Benz","MB","16S-2280-TD / 16S-2180-TO","Vehículo"},
			{"Mercedes Benz","MB","16S-2321-TD / 16S-2325TD","Vehículo"},
			{"Mercedes Benz","MB","16S-2525-TO / 16S-2320-TD","Vehículo"},
			{"Mercedes Benz","MB","1714","Vehículo"},
			{"Mercedes Benz","MB","1715","Vehículo"},
			{"Mercedes Benz","MB","1718","Vehículo"},
			{"Mercedes Benz","MB","1718 M","Vehículo"},
			{"Mercedes Benz","MB","1720 6x2","Vehículo"},
			{"Mercedes Benz","MB","1721","Vehículo"},
			{"Mercedes Benz","MB","1722","Vehículo"},
			{"Mercedes Benz","MB","1723","Vehículo"},
			{"Mercedes Benz","MB","1725","Vehículo"},
			{"Mercedes Benz","MB","1728","Vehículo"},
			{"Mercedes Benz","MB","1728A","Vehículo"},
			{"Mercedes Benz","MB","1820 BRAS.","Vehículo"},
			{"Mercedes Benz","MB","1835","Vehículo"},
			{"Mercedes Benz","MB","1924","Vehículo"},
			{"Mercedes Benz","MB","1929","Vehículo"},
			{"Mercedes Benz","MB","1932","Vehículo"},
			{"Mercedes Benz","MB","1933","Vehículo"},
			{"Mercedes Benz","MB","1934","Vehículo"},
			{"Mercedes Benz","MB","1935","Vehículo"},
			{"Mercedes Benz","MB","1938","Vehículo"},
			{"Mercedes Benz","MB","1938-S","Vehículo"},
			{"Mercedes Benz","MB","1938 - Eletrônico","Vehículo"},
			{"Mercedes Benz","MB","1938LS","Vehículo"},
			{"Mercedes Benz","MB","1941","Vehículo"},
			{"Mercedes Benz","MB","1942","Vehículo"},
			{"Mercedes Benz","MB","1944-S","Vehículo"},
			{"Mercedes Benz","MB","1972","Vehículo"},
			{"Mercedes Benz","MB","2013","Vehículo"},
			{"Mercedes Benz","MB","2014","Vehículo"},
			{"Mercedes Benz","MB","2017","Vehículo"},
			{"Mercedes Benz","MB","2035S / 2040S / 2044S","Vehículo"},
			{"Mercedes Benz","MB","2213","Vehículo"},
			{"Mercedes Benz","MB","2214","Vehículo"},
			{"Mercedes Benz","MB","2216","Vehículo"},
			{"Mercedes Benz","MB","2217","Vehículo"},
			{"Mercedes Benz","MB","2219","Vehículo"},
			{"Mercedes Benz","MB","2220","Vehículo"},
			{"Mercedes Benz","MB","2222","Vehículo"},
			{"Mercedes Benz","MB","2225","Vehículo"},
			{"Mercedes Benz","MB","2314","Vehículo"},
			{"Mercedes Benz","MB","2318","Vehículo"},
			{"Mercedes Benz","MB","2325","Vehículo"},
			{"Mercedes Benz","MB","2414","Vehículo"},
			{"Mercedes Benz","MB","2418","Vehículo"},
			{"Mercedes Benz","MB","2423B","Vehículo"},
			{"Mercedes Benz","MB","2423B Betoneira","Vehículo"},
			{"Mercedes Benz","MB","2423CK - C/Tomada de força","Vehículo"},
			{"Mercedes Benz","MB","2423K","Vehículo"},
			{"Mercedes Benz","MB","2423K com tomada de força","Vehículo"},
			{"Mercedes Benz","MB","2424","Vehículo"},
			{"Mercedes Benz","MB","2425","Vehículo"},
			{"Mercedes Benz","MB","2428 6x4","Vehículo"},
			{"Mercedes Benz","MB","2533","Vehículo"},
			{"Mercedes Benz","MB","2635","Vehículo"},
			{"Mercedes Benz","MB","2636","Vehículo"},
			{"Mercedes Benz","MB","2638","Vehículo"},
			{"Mercedes Benz","MB","2638 - Eletrônico","Vehículo"},
			{"Mercedes Benz","MB","2638 ELETRONICO","Motor"},
			{"Mercedes Benz","MB","2638 Eletrônico","Motor"},
			{"Mercedes Benz","MB","2825","Vehículo"},
			{"Mercedes Benz","MB","2825BK/2823/2828BK/2831 6X4","Vehículo"},
			{"Mercedes Benz","MB","2826","Vehículo"},
			{"Mercedes Benz","MB","2828","Vehículo"},
			{"Mercedes Benz","MB","2831","Vehículo"},
			{"Mercedes Benz","MB","3340/S/3344/S/3340K/4144K","Vehículo"},
			{"Mercedes Benz","MB","362","Vehículo"},
			{"Mercedes Benz","MB","364","Vehículo"},
			{"Mercedes Benz","MB","370","Vehículo"},
			{"Mercedes Benz","MB","371","Vehículo"},
			{"Mercedes Benz","MB","371R","Vehículo"},
			{"Mercedes Benz","MB","371RS","Vehículo"},
			{"Mercedes Benz","MB","400","Vehículo"},
			{"Mercedes Benz","MB","608","Vehículo"},
			{"Mercedes Benz","MB","608D","Vehículo"},
			{"Mercedes Benz","MB","708","Vehículo"},
			{"Mercedes Benz","MB","709","Vehículo"},
			{"Mercedes Benz","MB","710","Vehículo"},
			{"Mercedes Benz","MB","712","Vehículo"},
			{"Mercedes Benz","MB","712 C","Vehículo"},
			{"Mercedes Benz","MB","8S-1350 ( Mercedes )","Caja de Cambio"},
			{"Mercedes Benz","MB","912","Vehículo"},
			{"Mercedes Benz","MB","912C","Vehículo"},
			{"Mercedes Benz","MB","914","Vehículo"},
			{"Mercedes Benz","MB","914C","Vehículo"},
			{"Mercedes Benz","MB","915","Vehículo"},
			{"Mercedes Benz","MB","915C","Vehículo"},
			{"Mercedes Benz","MB","ACCELO 710-C","Vehículo"},
			{"Mercedes Benz","MB","ACCELO 915-C","Vehículo"},
			{"Mercedes Benz","MB","AK6-80 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","AL 4","Eje"},
			{"Mercedes Benz","MB","Atego - 1315/1418/1518/1718","Caja de Cambio"},
			{"Mercedes Benz","MB","ATEGO - 1315/1418/1518/1718","Vehículo"},
			{"Mercedes Benz","MB","ATEGO - 1318","Vehículo"},
			{"Mercedes Benz","MB","Atego 1315","Vehículo"},
			{"Mercedes Benz","MB","ATEGO 1718","Vehículo"},
			{"Mercedes Benz","MB","ATEGO 1725","Vehículo"},
			{"Mercedes Benz","MB","Atego 1725A 4x4","Vehículo"},
			{"Mercedes Benz","MB","Atego 2423 - 2425 6x2","Vehículo"},
			{"Mercedes Benz","MB","ATEGO 2425","Vehículo"},
			{"Mercedes Benz","MB","AXOR 1933","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2035","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2035S","Vehículo"},
			{"Mercedes Benz","MB","AXOR 20405","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2040S","Vehículo"},
			{"Mercedes Benz","MB","AXOR 20445","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2044S","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2533","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2535S","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2540","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2540S","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2544","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2625/2628/2826","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2640","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2644","Vehículo"},
			{"Mercedes Benz","MB","AXOR 2644S","Vehículo"},
			{"Mercedes Benz","MB","Axor 2831","Vehículo"},
			{"Mercedes Benz","MB","AXOR 3340 / 3344","Vehículo"},
			{"Mercedes Benz","MB","BR 400","Motor"},
			{"Mercedes Benz","MB","CARA CHATA","Vehículo"},
			{"Mercedes Benz","MB","DIANTEIRO","Eje"},
			{"Mercedes Benz","MB","Engrenagem 30 dentes","Vehículo"},
			{"Mercedes Benz","MB","FREIO A AR","Eje"},
			{"Mercedes Benz","MB","FS-5306 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","FS-6206 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","FS-6209A (MB)","Caja de Cambio"},
			{"Mercedes Benz","MB","FS-6306 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","FS-8209A (MB)","Caja de Cambio"},
			{"Mercedes Benz","MB","FSK 1938S","Vehículo"},
			{"Mercedes Benz","MB","FSO-4305 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","FSO-4305 A/B/C (MBB)","Caja de Cambio"},
			{"Mercedes Benz","MB","FSO-4405 (Mercedes-Benz)","Caja de Cambio"},
			{"Mercedes Benz","MB","FSO-4405A","Caja de Cambio"},
			{"Mercedes Benz","MB","FSO-4405C","Caja de Cambio"},
			{"Mercedes Benz","MB","Furotratker","Vehículo"},
			{"Mercedes Benz","MB","G-210","Caja de Cambio"},
			{"Mercedes Benz","MB","G-211","Caja de Cambio"},
			{"Mercedes Benz","MB","G-216","Caja de Cambio"},
			{"Mercedes Benz","MB","G-221","Caja de Cambio"},
			{"Mercedes Benz","MB","G-230 / 260","Caja de Cambio"},
			{"Mercedes Benz","MB","G-231","Caja de Cambio"},
			{"Mercedes Benz","MB","G-240","Caja de Cambio"},
			{"Mercedes Benz","MB","G-260","Caja de Cambio"},
			{"Mercedes Benz","MB","G-280","Caja de Cambio"},
			{"Mercedes Benz","MB","G-330","Caja de Cambio"},
			{"Mercedes Benz","MB","G-60","Caja de Cambio"},
			{"Mercedes Benz","MB","G-60 1","Caja de Cambio"},
			{"Mercedes Benz","MB","G-85","Caja de Cambio"},
			{"Mercedes Benz","MB","G2-20","Caja de Cambio"},
			{"Mercedes Benz","MB","G2-24","Caja de Cambio"},
			{"Mercedes Benz","MB","G2-24 - Argentina","Caja de Cambio"},
			{"Mercedes Benz","MB","G3-36","Caja de Cambio"},
			{"Mercedes Benz","MB","G3-40","Caja de Cambio"},
			{"Mercedes Benz","MB","G3-50","Caja de Cambio"},
			{"Mercedes Benz","MB","G3-60","Caja de Cambio"},
			{"Mercedes Benz","MB","G3-60 - Antigo (Série 337)","Caja de Cambio"},
			{"Mercedes Benz","MB","G3-61","Caja de Cambio"},
			{"Mercedes Benz","MB","GO-190","Vehículo"},
			{"Mercedes Benz","MB","GO-190","Caja de Cambio"},
			{"Mercedes Benz","MB","HD-21","Vehículo"},
			{"Mercedes Benz","MB","HD-4","Vehículo"},
			{"Mercedes Benz","MB","HD-4 1º Eixo","Eje"},
			{"Mercedes Benz","MB","HD-4 2º Eixo","Eje"},
			{"Mercedes Benz","MB","HD-4/01/02","Eje"},
			{"Mercedes Benz","MB","HD-4/05","Eje"},
			{"Mercedes Benz","MB","HD-7","Eje"},
			{"Mercedes Benz","MB","HD-7 (AXOR 2035S/2535S)","Vehículo"},
			{"Mercedes Benz","MB","HL-2","Eje"},
			{"Mercedes Benz","MB","HL-4","Eje"},
			{"Mercedes Benz","MB","HL-4/01","Eje"},
			{"Mercedes Benz","MB","HL-4/04","Eje"},
			{"Mercedes Benz","MB","HL-4/061 / 062","Eje"},
			{"Mercedes Benz","MB","HL-5","Eje"},
			{"Mercedes Benz","MB","HL-5 (Freio a Ar - ano 82/...","Eje"},
			{"Mercedes Benz","MB","HL-5z (Reduzido)","Eje"},
			{"Mercedes Benz","MB","HL-6","Eje"},
			{"Mercedes Benz","MB","HL-7","Eje"},
			{"Mercedes Benz","MB","HL 0-15","Eje"},
			{"Mercedes Benz","MB","HL 4","Eje"},
			{"Mercedes Benz","MB","HO-4/01","Eje"},
			{"Mercedes Benz","MB","HO-7","Eje"},
			{"Mercedes Benz","MB","HPL 1625","Vehículo"},
			{"Mercedes Benz","MB","HPL 2325","Vehículo"},
			{"Mercedes Benz","MB","HPN-1625","Vehículo"},
			{"Mercedes Benz","MB","HPN-2325","Vehículo"},
			{"Mercedes Benz","MB","KSK-1938 S/33","Vehículo"},
			{"Mercedes Benz","MB","L-1111","Vehículo"},
			{"Mercedes Benz","MB","L-1113","Vehículo"},
			{"Mercedes Benz","MB","L-1114","Vehículo"},
			{"Mercedes Benz","MB","L-1116","Vehículo"},
			{"Mercedes Benz","MB","L-1118","Vehículo"},
			{"Mercedes Benz","MB","L-1214","Vehículo"},
			{"Mercedes Benz","MB","L-1218","Vehículo"},
			{"Mercedes Benz","MB","L-1218 EL","Vehículo"},
			{"Mercedes Benz","MB","L-121C/98 (MBB)","Vehículo"},
			{"Mercedes Benz","MB","L-1313","Vehículo"},
			{"Mercedes Benz","MB","L-1314","Vehículo"},
			{"Mercedes Benz","MB","L-1316","Vehículo"},
			{"Mercedes Benz","MB","L-1318","Vehículo"},
			{"Mercedes Benz","MB","L-1319","Vehículo"},
			{"Mercedes Benz","MB","L-1414","Vehículo"},
			{"Mercedes Benz","MB","L-1417","Vehículo"},
			{"Mercedes Benz","MB","L-1418","Vehículo"},
			{"Mercedes Benz","MB","L-1418 EL","Vehículo"},
			{"Mercedes Benz","MB","L-1513","Vehículo"},
			{"Mercedes Benz","MB","L-1516","Vehículo"},
			{"Mercedes Benz","MB","L-1518","Vehículo"},
			{"Mercedes Benz","MB","L-1519","Vehículo"},
			{"Mercedes Benz","MB","L-1520","Vehículo"},
			{"Mercedes Benz","MB","L-1614","Vehículo"},
			{"Mercedes Benz","MB","L-1618","Vehículo"},
			{"Mercedes Benz","MB","L-1620","Vehículo"},
			{"Mercedes Benz","MB","L-1620 6x2","Vehículo"},
			{"Mercedes Benz","MB","L-1620 Eletronico","Vehículo"},
			{"Mercedes Benz","MB","L-1621","Vehículo"},
			{"Mercedes Benz","MB","L-1622","Vehículo"},
			{"Mercedes Benz","MB","L-1622 6x2","Vehículo"},
			{"Mercedes Benz","MB","L-1624","Vehículo"},
			{"Mercedes Benz","MB","L-1625","Vehículo"},
			{"Mercedes Benz","MB","L-1630","Vehículo"},
			{"Mercedes Benz","MB","L-1632","Vehículo"},
			{"Mercedes Benz","MB","L-1634","Vehículo"},
			{"Mercedes Benz","MB","L-1721","Vehículo"},
			{"Mercedes Benz","MB","L-1924A","Vehículo"},
			{"Mercedes Benz","MB","L-1929","Vehículo"},
			{"Mercedes Benz","MB","L-1932","Vehículo"},
			{"Mercedes Benz","MB","L-1933","Vehículo"},
			{"Mercedes Benz","MB","L-1934","Vehículo"},
			{"Mercedes Benz","MB","L-1935","Vehículo"},
			{"Mercedes Benz","MB","L-1938","Vehículo"},
			{"Mercedes Benz","MB","L-1941","Vehículo"},
			{"Mercedes Benz","MB","L-1942","Vehículo"},
			{"Mercedes Benz","MB","L-1944","Vehículo"},
			{"Mercedes Benz","MB","L-2013","Vehículo"},
			{"Mercedes Benz","MB","L-2014","Vehículo"},
			{"Mercedes Benz","MB","L-2213","Vehículo"},
			{"Mercedes Benz","MB","L-2219","Vehículo"},
			{"Mercedes Benz","MB","L-2220","Vehículo"},
			{"Mercedes Benz","MB","L-2225","Vehículo"},
			{"Mercedes Benz","MB","L-2314","Vehículo"},
			{"Mercedes Benz","MB","L-2318","Vehículo"},
			{"Mercedes Benz","MB","L-2325","Vehículo"},
			{"Mercedes Benz","MB","L-2418","Vehículo"},
			{"Mercedes Benz","MB","L-2425","Eje"},
			{"Mercedes Benz","MB","L-2625","Vehículo"},
			{"Mercedes Benz","MB","L-2628","Vehículo"},
			{"Mercedes Benz","MB","L-2635","Vehículo"},
			{"Mercedes Benz","MB","L-2638","Vehículo"},
			{"Mercedes Benz","MB","L-2654","Vehículo"},
			{"Mercedes Benz","MB","L-608 D","Vehículo"},
			{"Mercedes Benz","MB","L-708","Vehículo"},
			{"Mercedes Benz","MB","L-709","Vehículo"},
			{"Mercedes Benz","MB","L-709 - Argentina","Vehículo"},
			{"Mercedes Benz","MB","L-710 (MBB)","Vehículo"},
			{"Mercedes Benz","MB","L-914C/98 (MBB)","Vehículo"},
			{"Mercedes Benz","MB","L-915/98 (MBB)","Vehículo"},
			{"Mercedes Benz","MB","L 912","Vehículo"},
			{"Mercedes Benz","MB","L/LO-709 TURBO","Vehículo"},
			{"Mercedes Benz","MB","L/LO-914 TURBO INTERCULER","Vehículo"},
			{"Mercedes Benz","MB","L/LS 1632","Vehículo"},
			{"Mercedes Benz","MB","L/LS 1938","Vehículo"},
			{"Mercedes Benz","MB","L/LS 1942","Vehículo"},
			{"Mercedes Benz","MB","L1634","Vehículo"},
			{"Mercedes Benz","MB","L98-1215C","Vehículo"},
			{"Mercedes Benz","MB","L98-914C","Vehículo"},
			{"Mercedes Benz","MB","L98-915","Vehículo"},
			{"Mercedes Benz","MB","L98/LO-914","Vehículo"},
			{"Mercedes Benz","MB","LA-1313","Vehículo"},
			{"Mercedes Benz","MB","LA-1414","Vehículo"},
			{"Mercedes Benz","MB","LA-2423","Eje"},
			{"Mercedes Benz","MB","LA-2425","Eje"},
			{"Mercedes Benz","MB","LA-2428","Eje"},
			{"Mercedes Benz","MB","LA-LK-LAK","Eje"},
			{"Mercedes Benz","MB","LB-2219","Vehículo"},
			{"Mercedes Benz","MB","LB-2220","Vehículo"},
			{"Mercedes Benz","MB","LB-2318","Vehículo"},
			{"Mercedes Benz","MB","LB-2325","Vehículo"},
			{"Mercedes Benz","MB","LB-2425","Vehículo"},
			{"Mercedes Benz","MB","LB-3425","Vehículo"},
			{"Mercedes Benz","MB","LG-1819","Vehículo"},
			{"Mercedes Benz","MB","LG-1820","Vehículo"},
			{"Mercedes Benz","MB","LK-1113","Vehículo"},
			{"Mercedes Benz","MB","LK-1114","Vehículo"},
			{"Mercedes Benz","MB","LK-1118","Vehículo"},
			{"Mercedes Benz","MB","LK-1214","Vehículo"},
			{"Mercedes Benz","MB","LK-1218","Vehículo"},
			{"Mercedes Benz","MB","LK-1218 EL","Vehículo"},
			{"Mercedes Benz","MB","LK-1313","Vehículo"},
			{"Mercedes Benz","MB","LK-1314","Vehículo"},
			{"Mercedes Benz","MB","LK-1316","Vehículo"},
			{"Mercedes Benz","MB","LK-1318","Vehículo"},
			{"Mercedes Benz","MB","LK-1319","Vehículo"},
			{"Mercedes Benz","MB","LK-1414","Vehículo"},
			{"Mercedes Benz","MB","LK-1418","Vehículo"},
			{"Mercedes Benz","MB","LK-1514","Vehículo"},
			{"Mercedes Benz","MB","LK-1516","Vehículo"},
			{"Mercedes Benz","MB","LK-1517","Vehículo"},
			{"Mercedes Benz","MB","LK-1518","Vehículo"},
			{"Mercedes Benz","MB","LK-1519","Vehículo"},
			{"Mercedes Benz","MB","LK-1520","Vehículo"},
			{"Mercedes Benz","MB","LK-1614","Vehículo"},
			{"Mercedes Benz","MB","LK-1618","Vehículo"},
			{"Mercedes Benz","MB","LK-1621","Vehículo"},
			{"Mercedes Benz","MB","LK-1623","Vehículo"},
			{"Mercedes Benz","MB","LK-1630","Vehículo"},
			{"Mercedes Benz","MB","LK-1632","Vehículo"},
			{"Mercedes Benz","MB","LK-1634","Vehículo"},
			{"Mercedes Benz","MB","LK-172 1995","Vehículo"},
			{"Mercedes Benz","MB","LK-1721","Vehículo"},
			{"Mercedes Benz","MB","LK-1924A","Vehículo"},
			{"Mercedes Benz","MB","LK-1929","Vehículo"},
			{"Mercedes Benz","MB","LK-1932","Vehículo"},
			{"Mercedes Benz","MB","LK-1933","Vehículo"},
			{"Mercedes Benz","MB","LK-1934","Vehículo"},
			{"Mercedes Benz","MB","LK-1935","Vehículo"},
			{"Mercedes Benz","MB","LK-1938","Vehículo"},
			{"Mercedes Benz","MB","LK-1941","Vehículo"},
			{"Mercedes Benz","MB","LK-1942","Vehículo"},
			{"Mercedes Benz","MB","LK-1944","Vehículo"},
			{"Mercedes Benz","MB","LK-2219","Vehículo"},
			{"Mercedes Benz","MB","LK-2220","Vehículo"},
			{"Mercedes Benz","MB","LK-2318","Vehículo"},
			{"Mercedes Benz","MB","LK-2325","Vehículo"},
			{"Mercedes Benz","MB","LK-2420","Vehículo"},
			{"Mercedes Benz","MB","LK-2425","Eje"},
			{"Mercedes Benz","MB","LK-2635","Vehículo"},
			{"Mercedes Benz","MB","LK-2636","Vehículo"},
			{"Mercedes Benz","MB","LK-2638","Vehículo"},
			{"Mercedes Benz","MB","LK 1620","Vehículo"},
			{"Mercedes Benz","MB","LK 2418","Vehículo"},
			{"Mercedes Benz","MB","LK 2636","Vehículo"},
			{"Mercedes Benz","MB","LK 2638","Vehículo"},
			{"Mercedes Benz","MB","LKS-2638","Vehículo"},
			{"Mercedes Benz","MB","LN-710","Vehículo"},
			{"Mercedes Benz","MB","LO-610","Vehículo"},
			{"Mercedes Benz","MB","LO-812","Vehículo"},
			{"Mercedes Benz","MB","LO-812 TURBO","Vehículo"},
			{"Mercedes Benz","MB","LO-814","Vehículo"},
			{"Mercedes Benz","MB","LO-814 TURBO INTERCULER","Vehículo"},
			{"Mercedes Benz","MB","LO-914","Vehículo"},
			{"Mercedes Benz","MB","LO-915 (MBB)","Vehículo"},
			{"Mercedes Benz","MB","LO 809","Vehículo"},
			{"Mercedes Benz","MB","LP-312","Vehículo"},
			{"Mercedes Benz","MB","LP-321","Vehículo"},
			{"Mercedes Benz","MB","LPO-1113","Vehículo"},
			{"Mercedes Benz","MB","LPO-1313","Vehículo"},
			{"Mercedes Benz","MB","LPO-2013","Vehículo"},
			{"Mercedes Benz","MB","LS-1113","Vehículo"},
			{"Mercedes Benz","MB","LS-1519","Vehículo"},
			{"Mercedes Benz","MB","LS-1524","Vehículo"},
			{"Mercedes Benz","MB","LS-1525","Vehículo"},
			{"Mercedes Benz","MB","LS-1621","Vehículo"},
			{"Mercedes Benz","MB","LS-1622","Eje"},
			{"Mercedes Benz","MB","LS-1630","Vehículo"},
			{"Mercedes Benz","MB","LS-1631","Vehículo"},
			{"Mercedes Benz","MB","LS-1632","Vehículo"},
			{"Mercedes Benz","MB","LS-1633","Vehículo"},
			{"Mercedes Benz","MB","LS-1634","Vehículo"},
			{"Mercedes Benz","MB","LS-1924A","Vehículo"},
			{"Mercedes Benz","MB","LS-1929","Vehículo"},
			{"Mercedes Benz","MB","LS-1932","Vehículo"},
			{"Mercedes Benz","MB","LS-1933","Vehículo"},
			{"Mercedes Benz","MB","LS-1934","Vehículo"},
			{"Mercedes Benz","MB","LS-1935","Vehículo"},
			{"Mercedes Benz","MB","LS-1938","Vehículo"},
			{"Mercedes Benz","MB","LS-1941","Vehículo"},
			{"Mercedes Benz","MB","LS-1942","Vehículo"},
			{"Mercedes Benz","MB","LS-1944","Vehículo"},
			{"Mercedes Benz","MB","LS-2629","Vehículo"},
			{"Mercedes Benz","MB","LS-2635","Vehículo"},
			{"Mercedes Benz","MB","LS-2638","Vehículo"},
			{"Mercedes Benz","MB","LS 1625","Vehículo"},
			{"Mercedes Benz","MB","LS 1924","Vehículo"},
			{"Mercedes Benz","MB","LS 1932","Vehículo"},
			{"Mercedes Benz","MB","LS 1938","Caja de Cambio"},
			{"Mercedes Benz","MB","MB LS 1938","Eje"},
			{"Mercedes Benz","MB","MBB 710","Vehículo"},
			{"Mercedes Benz","MB","MBB 710C","Vehículo"},
			{"Mercedes Benz","MB","MBB ACCELO 710C","Vehículo"},
			{"Mercedes Benz","MB","MBB Accelo 915C","Vehículo"},
			{"Mercedes Benz","MB","Micro ônibus LO-812","Vehículo"},
			{"Mercedes Benz","MB","Micro ônibus LO-914","Vehículo"},
			{"Mercedes Benz","MB","Micro ônibus LO 712","Vehículo"},
			{"Mercedes Benz","MB","NR 4/22","Eje"},
			{"Mercedes Benz","MB","O-326","Vehículo"},
			{"Mercedes Benz","MB","O-352","Vehículo"},
			{"Mercedes Benz","MB","O-355","Vehículo"},
			{"Mercedes Benz","MB","O-362","Vehículo"},
			{"Mercedes Benz","MB","O-364","Vehículo"},
			{"Mercedes Benz","MB","O-364 12R","Vehículo"},
			{"Mercedes Benz","MB","O-364 13R","Vehículo"},
			{"Mercedes Benz","MB","O-370","Vehículo"},
			{"Mercedes Benz","MB","O-370 R","Vehículo"},
			{"Mercedes Benz","MB","O-370 RS","Vehículo"},
			{"Mercedes Benz","MB","O-370 RSD","Vehículo"},
			{"Mercedes Benz","MB","O-371","Vehículo"},
			{"Mercedes Benz","MB","O-371-RSD","Vehículo"},
			{"Mercedes Benz","MB","O-371 PST","Vehículo"},
			{"Mercedes Benz","MB","O-371 RS","Vehículo"},
			{"Mercedes Benz","MB","O-371 RSL","Vehículo"},
			{"Mercedes Benz","MB","O-371 U","Vehículo"},
			{"Mercedes Benz","MB","O-371 UP","Vehículo"},
			{"Mercedes Benz","MB","O-371R","Vehículo"},
			{"Mercedes Benz","MB","O-374RS","Vehículo"},
			{"Mercedes Benz","MB","O-400","Vehículo"},
			{"Mercedes Benz","MB","O-400 RS","Vehículo"},
			{"Mercedes Benz","MB","O-400 RSD","Vehículo"},
			{"Mercedes Benz","MB","O-400 RSL","Vehículo"},
			{"Mercedes Benz","MB","O-400 UP","Vehículo"},
			{"Mercedes Benz","MB","O-400 UPA","Vehículo"},
			{"Mercedes Benz","MB","O-500","Vehículo"},
			{"Mercedes Benz","MB","O-500 M - 1725","Vehículo"},
			{"Mercedes Benz","MB","O-500 R","Vehículo"},
			{"Mercedes Benz","MB","O-500 R/RS/RSD","Vehículo"},
			{"Mercedes Benz","MB","O-500 RS","Vehículo"},
			{"Mercedes Benz","MB","O-500 RSD","Vehículo"},
			{"Mercedes Benz","MB","O-500 RSL","Vehículo"},
			{"Mercedes Benz","MB","O-500 U - 1725","Vehículo"},
			{"Mercedes Benz","MB","O 374","Vehículo"},
			{"Mercedes Benz","MB","O 500 M","Caja de Cambio"},
			{"Mercedes Benz","MB","O 500 U","Caja de Cambio"},
			{"Mercedes Benz","MB","O 500 U","Motor"},
			{"Mercedes Benz","MB","O400","Vehículo"},
			{"Mercedes Benz","MB","OF-1113","Vehículo"},
			{"Mercedes Benz","MB","OF-1114 TURBO INTERCULER","Vehículo"},
			{"Mercedes Benz","MB","OF-1115","Vehículo"},
			{"Mercedes Benz","MB","OF-1214 TURBO INTERCULER","Vehículo"},
			{"Mercedes Benz","MB","OF-1313","Vehículo"},
			{"Mercedes Benz","MB","OF-1315","Vehículo"},
			{"Mercedes Benz","MB","OF-1317","Eje"},
			{"Mercedes Benz","MB","OF-1318","Vehículo"},
			{"Mercedes Benz","MB","OF-1415","Vehículo"},
			{"Mercedes Benz","MB","OF-1417","Vehículo"},
			{"Mercedes Benz","MB","OF-1418","Vehículo"},
			{"Mercedes Benz","MB","OF-1518","Vehículo"},
			{"Mercedes Benz","MB","OF-1618","Vehículo"},
			{"Mercedes Benz","MB","OF-1618M","Vehículo"},
			{"Mercedes Benz","MB","OF-1621","Vehículo"},
			{"Mercedes Benz","MB","OF-1722","Vehículo"},
			{"Mercedes Benz","MB","OF-1722 M","Vehículo"},
			{"Mercedes Benz","MB","OF-2013","Vehículo"},
			{"Mercedes Benz","MB","OF-2325","Vehículo"},
			{"Mercedes Benz","MB","OF-709 TURBO","Vehículo"},
			{"Mercedes Benz","MB","OF-712 TURBO","Vehículo"},
			{"Mercedes Benz","MB","OF-812 TURBO","Vehículo"},
			{"Mercedes Benz","MB","OF-912 TURBO","Vehículo"},
			{"Mercedes Benz","MB","OF 1318","Vehículo"},
			{"Mercedes Benz","MB","OF 1414","Vehículo"},
			{"Mercedes Benz","MB","OF 1617","Vehículo"},
			{"Mercedes Benz","MB","OF 1620","Vehículo"},
			{"Mercedes Benz","MB","OF 1721","Vehículo"},
			{"Mercedes Benz","MB","OF 812","Vehículo"},
			{"Mercedes Benz","MB","OF1620","Vehículo"},
			{"Mercedes Benz","MB","OH-1113","Vehículo"},
			{"Mercedes Benz","MB","OH-1313","Vehículo"},
			{"Mercedes Benz","MB","OH-1315","Vehículo"},
			{"Mercedes Benz","MB","OH-1417","Vehículo"},
			{"Mercedes Benz","MB","OH-1418","Vehículo"},
			{"Mercedes Benz","MB","OH-1419","Vehículo"},
			{"Mercedes Benz","MB","OH-1420","Vehículo"},
			{"Mercedes Benz","MB","OH-1517","Vehículo"},
			{"Mercedes Benz","MB","OH-1520","Vehículo"},
			{"Mercedes Benz","MB","OH 1318","Vehículo"},
			{"Mercedes Benz","MB","OH 1421","Vehículo"},
			{"Mercedes Benz","MB","OH 1421L","Vehículo"},
			{"Mercedes Benz","MB","OH 1621","Vehículo"},
			{"Mercedes Benz","MB","OH 1621L","Vehículo"},
			{"Mercedes Benz","MB","OH 1720","Vehículo"},
			{"Mercedes Benz","MB","OHL-1620","Vehículo"},
			{"Mercedes Benz","MB","OM 1420","Motor"},
			{"Mercedes Benz","MB","OM 1518","Motor"},
			{"Mercedes Benz","MB","OM 314","Motor"},
			{"Mercedes Benz","MB","OM 352","Motor"},
			{"Mercedes Benz","MB","OM 352 A","Motor"},
			{"Mercedes Benz","MB","OM 355","Motor"},
			{"Mercedes Benz","MB","OM 355 A","Motor"},
			{"Mercedes Benz","MB","OM 355 LA","Motor"},
			{"Mercedes Benz","MB","OM 355/5","Motor"},
			{"Mercedes Benz","MB","OM 355/5 A","Motor"},
			{"Mercedes Benz","MB","OM 364","Motor"},
			{"Mercedes Benz","MB","OM 364 A","Motor"},
			{"Mercedes Benz","MB","OM 364 A / 20°","Motor"},
			{"Mercedes Benz","MB","OM 364 LA","Motor"},
			{"Mercedes Benz","MB","OM 364 LA / 20°","Motor"},
			{"Mercedes Benz","MB","OM 366","Motor"},
			{"Mercedes Benz","MB","OM 366 A","Motor"},
			{"Mercedes Benz","MB","OM 366 Aspirado","Motor"},
			{"Mercedes Benz","MB","OM 366 LA","Motor"},
			{"Mercedes Benz","MB","OM 366 LA II","Motor"},
			{"Mercedes Benz","MB","OM 447","Motor"},
			{"Mercedes Benz","MB","OM 447 LA","Motor"},
			{"Mercedes Benz","MB","OM 449","Motor"},
			{"Mercedes Benz","MB","OM 457 LA","Motor"},
			{"Mercedes Benz","MB","OM 460LA","Motor"},
			{"Mercedes Benz","MB","OM 904","Motor"},
			{"Mercedes Benz","MB","OM 904 LA","Motor"},
			{"Mercedes Benz","MB","OM 906 LA","Motor"},
			{"Mercedes Benz","MB","OM 924 LA","Motor"},
			{"Mercedes Benz","MB","OM 926 LA","Motor"},
			{"Mercedes Benz","MB","OM355","Motor"},
			{"Mercedes Benz","MB","R, RS, RSD","Eje"},
			{"Mercedes Benz","MB","Reparo Completo (roletado)","Vehículo"},
			{"Mercedes Benz","MB","RODOVIÁRIO","Vehículo"},
			{"Mercedes Benz","MB","RS-23-240","Eje"},
			{"Mercedes Benz","MB","RS-23-245","Vehículo"},
			{"Mercedes Benz","MB","S5-42","Caja de Cambio"},
			{"Mercedes Benz","MB","S5-420","Caja de Cambio"},
			{"Mercedes Benz","MB","S5-680","Caja de Cambio"},
			{"Mercedes Benz","MB","S5-680 (Mercedes - Versão 010)","Caja de Cambio"},
			{"Mercedes Benz","MB","S5-680 (Mercedes - Versão 031)","Caja de Cambio"},
			{"Mercedes Benz","MB","S5-680 (Mercedes - Versão 042)","Caja de Cambio"},
			{"Mercedes Benz","MB","S5-820 ( Mercedes )","Caja de Cambio"},
			{"Mercedes Benz","MB","S6-680 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","S6-80 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","S6-820 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","S6-90 (Mercedes)","Caja de Cambio"},
			{"Mercedes Benz","MB","SPRINTER 310 D","Eje"},
			{"Mercedes Benz","MB","SPRINTER 311 CDI","Eje"},
			{"Mercedes Benz","MB","Sprinter 312","Vehículo"},
			{"Mercedes Benz","MB","SPRINTER 312 D","Eje"},
			{"Mercedes Benz","MB","SPRINTER 313 CDI","Eje"},
			{"Mercedes Benz","MB","Sprinter 412","Vehículo"},
			{"Mercedes Benz","MB","TRASEIRO","Eje"},
			{"Metalfor","MET","6300 TURBO","Vehículo"},
			{"Metalfor","MET","FSO-4305 (Metalfor)","Caja de Cambio"},
			{"Metalfor","MET","PULVERIZADOR","Vehículo"},
			{"Modasa","MDS","CAMIÓN & BUS","Vehículo"},
			{"Modasa","MDS","FSO-4305 (Modasa)","Caja de Cambio"},
			{"MWM","MWM","Motor MWM","Motor"},
			{"Nissan","NIS","FSO-2405J","Caja de Cambio"},
			{"OTROS","OTR","COLCHA - Pulverizadores","Vehículo"},
			{"OTROS","OTR","EL DETALLE OA-101","Vehículo"},
			{"OTROS","OTR","ITALFOR - Pulverizadores","Vehículo"},
			{"OTROS","OTR","MÜLLER TM-14","Vehículo"},
			{"OTROS","OTR","PAUNY - MICRO MT","Vehículo"},
			{"OTROS","OTR","RK 425B ( Randon )","Vehículo"},
			{"OTROS","OTR","RK 430 ( Randon )","Vehículo"},
			{"Perkins","PER","Perkins","Motor"},
			{"Perkins","PER","Perkins 3-152 Injeção Indireta","Motor"},
			{"Perkins","PER","Perkins 4.203 Injeção Indireta","Motor"},
			{"Perkins","PER","Perkins 4236","Motor"},
			{"Randon","RND","16S-1650 ( Randon )","Vehículo"},
			{"Referencia","REF","4K-121-GP","Caja de Cambio"},
			{"Referencia","REF","4K 120 GP","Caja de Cambio"},
			{"Referencia","REF","4S 120GP","Caja de Cambio"},
			{"Referencia","REF","MS/RS-19-145 / 23-145","Eje"},
			{"Renault","RNT","16S-2180TO","Vehículo"},
			{"Scania","SCN","110","Vehículo"},
			{"Scania","SCN","111","Vehículo"},
			{"Scania","SCN","111S","Vehículo"},
			{"Scania","SCN","112","Vehículo"},
			{"Scania","SCN","112 HW","Vehículo"},
			{"Scania","SCN","113","Vehículo"},
			{"Scania","SCN","114","Vehículo"},
			{"Scania","SCN","124","Vehículo"},
			{"Scania","SCN","142","Vehículo"},
			{"Scania","SCN","143","Vehículo"},
			{"Scania","SCN","94","Vehículo"},
			{"Scania","SCN","AD-100","Eje"},
			{"Scania","SCN","BR-111","Vehículo"},
			{"Scania","SCN","BR-116","Vehículo"},
			{"Scania","SCN","DS-11","Motor"},
			{"Scania","SCN","DSC-11","Motor"},
			{"Scania","SCN","DSC 12","Motor"},
			{"Scania","SCN","F-113","Vehículo"},
			{"Scania","SCN","G-770 - Ônibus","Caja de Cambio"},
			{"Scania","SCN","G-770 - Ônibus (1ª seca)","Caja de Cambio"},
			{"Scania","SCN","G-776 - Ônibus","Caja de Cambio"},
			{"Scania","SCN","G-777 - Ônibus","Caja de Cambio"},
			{"Scania","SCN","GR-801","Caja de Cambio"},
			{"Scania","SCN","GR-801 Ônibus","Caja de Cambio"},
			{"Scania","SCN","GR-801R","Caja de Cambio"},
			{"Scania","SCN","GR-860","Caja de Cambio"},
			{"Scania","SCN","GR-870","Caja de Cambio"},
			{"Scania","SCN","GR-871","Caja de Cambio"},
			{"Scania","SCN","GR-900 - 8 marchas","Caja de Cambio"},
			{"Scania","SCN","GRS-900 - 6 marchas","Caja de Cambio"},
			{"Scania","SCN","K-112","Vehículo"},
			{"Scania","SCN","K-113","Vehículo"},
			{"Scania","SCN","L-110","Vehículo"},
			{"Scania","SCN","L-111","Vehículo"},
			{"Scania","SCN","LK-111","Vehículo"},
			{"Scania","SCN","LK-140","Vehículo"},
			{"Scania","SCN","LK-141","Vehículo"},
			{"Scania","SCN","P-114","Vehículo"},
			{"Scania","SCN","P-124","Vehículo"},
			{"Scania","SCN","P-94","Vehículo"},
			{"Scania","SCN","R-112","Vehículo"},
			{"Scania","SCN","R-113","Vehículo"},
			{"Scania","SCN","R-114","Vehículo"},
			{"Scania","SCN","R-124","Vehículo"},
			{"Scania","SCN","R-142","Vehículo"},
			{"Scania","SCN","R-143","Vehículo"},
			{"Scania","SCN","R-642 (Redução Central)","Eje"},
			{"Scania","SCN","R-651 (Redução Central)","Eje"},
			{"Scania","SCN","R-653 (Redução Central)","Eje"},
			{"Scania","SCN","R-660 (Redução Central)","Eje"},
			{"Scania","SCN","R-751 (Redução Central)","Eje"},
			{"Scania","SCN","R-752 (Redução Central)","Eje"},
			{"Scania","SCN","R-770 (Redução Central)","Eje"},
			{"Scania","SCN","R-780 (Redução Central)","Eje"},
			{"Scania","SCN","R-780 Series 3 e 4","Vehículo"},
			{"Scania","SCN","R-782","Eje"},
			{"Scania","SCN","RB-660","Eje"},
			{"Scania","SCN","RB-660 Dianteiro","Eje"},
			{"Scania","SCN","RP-831 (Redução Central)","Eje"},
			{"Scania","SCN","RPB-831 (Redução Central)","Eje"},
			{"Scania","SCN","Scania","Motor"},
			{"Scania","SCN","Scania","Vehículo"},
			{"Scania","SCN","Série 4 - 12 Litros","Motor"},
			{"Scania","SCN","T-112","Vehículo"},
			{"Scania","SCN","T-113","Vehículo"},
			{"Scania","SCN","T-114","Vehículo"},
			{"Scania","SCN","T-124","Vehículo"},
			{"Scania","SCN","T-142","Vehículo"},
			{"Scania","SCN","T-143","Vehículo"},
			{"Scania","SCN","tambor","Tambor de freno"},
			{"Scania","SCN","tambor","Eje"},
			{"Scania","SCN","TAMBOR DE FREIO","Vehículo"},
			{"Scania","SCN","TAMBOR DE FREIO","Eje"},
			{"Scania","SCN","TAMBOR DE FREIO TRAS","Eje"},
			{"Volkswagen","VW","14.140/150","Vehículo"},
			{"Volkswagen","VW","14.170BT","Vehículo"},
			{"Volkswagen","VW","14.180/200/220","Vehículo"},
			{"Volkswagen","VW","15.170/180/190","Vehículo"},
			{"Volkswagen","VW","15.180","Vehículo"},
			{"Volkswagen","VW","16.170/200/210/220/300","Vehículo"},
			{"Volkswagen","VW","16.180","Vehículo"},
			{"Volkswagen","VW","16.210","Vehículo"},
			{"Volkswagen","VW","16S-1300","Caja de Cambio"},
			{"Volkswagen","VW","16S-1300 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","16S-1650 ( Volks )","Caja de Cambio"},
			{"Volkswagen","VW","16S-221","Caja de Cambio"},
			{"Volkswagen","VW","16S-221","Caja de Cambio"},
			{"Volkswagen","VW","17.210","Vehículo"},
			{"Volkswagen","VW","17.210 OD","Vehículo"},
			{"Volkswagen","VW","17.210 ONIBUS","Vehículo"},
			{"Volkswagen","VW","17.210/220/250/300/310","Vehículo"},
			{"Volkswagen","VW","17.240 OD","Vehículo"},
			{"Volkswagen","VW","17.260","Vehículo"},
			{"Volkswagen","VW","18.210 Freio 15","Vehículo"},
			{"Volkswagen","VW","18.310","Vehículo"},
			{"Volkswagen","VW","18.320","Vehículo"},
			{"Volkswagen","VW","19-370 / 25-370 / 31-370","Vehículo"},
			{"Volkswagen","VW","19.310/320","Vehículo"},
			{"Volkswagen","VW","23.210/220/310","Vehículo"},
			{"Volkswagen","VW","23.330","Vehículo"},
			{"Volkswagen","VW","24.220/250","Vehículo"},
			{"Volkswagen","VW","240V (VW)","Caja de Cambio"},
			{"Volkswagen","VW","25.320","Vehículo"},
			{"Volkswagen","VW","26.260","Vehículo"},
			{"Volkswagen","VW","26.260/300/310","Vehículo"},
			{"Volkswagen","VW","280V","Caja de Cambio"},
			{"Volkswagen","VW","280VH","Caja de Cambio"},
			{"Volkswagen","VW","280VHD","Caja de Cambio"},
			{"Volkswagen","VW","31.320/370","Vehículo"},
			{"Volkswagen","VW","35.200/300","Vehículo"},
			{"Volkswagen","VW","390V","Caja de Cambio"},
			{"Volkswagen","VW","40.300","Vehículo"},
			{"Volkswagen","VW","BUS 16-180","Vehículo"},
			{"Volkswagen","VW","CL-450 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","E-NT 3200","Vehículo"},
			{"Volkswagen","VW","FS-2305","Caja de Cambio"},
			{"Volkswagen","VW","FS-4005 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-4005A/B (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-4205 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-4205A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5005 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5005A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5005A/C (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5106 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5205 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5205A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5205C (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5305","Caja de Cambio"},
			{"Volkswagen","VW","FS-5306 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-5405A","Caja de Cambio"},
			{"Volkswagen","VW","FS-5406A","Caja de Cambio"},
			{"Volkswagen","VW","FS-6205A","Caja de Cambio"},
			{"Volkswagen","VW","FS-6206 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-6306 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-6306A","Caja de Cambio"},
			{"Volkswagen","VW","FS-6306A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FS-6406A","Caja de Cambio"},
			{"Volkswagen","VW","FS-6406A/B","Caja de Cambio"},
			{"Volkswagen","VW","FS-6406B (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-5305 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-5305D (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-5405","Caja de Cambio"},
			{"Volkswagen","VW","FSB-5405A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-5406","Caja de Cambio"},
			{"Volkswagen","VW","FSB-5406A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-6206A","Caja de Cambio"},
			{"Volkswagen","VW","FSB-6406 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-6406A","Caja de Cambio"},
			{"Volkswagen","VW","FSB-6406A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-6406B","Caja de Cambio"},
			{"Volkswagen","VW","FSB-6406B (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSB-8406A","Caja de Cambio"},
			{"Volkswagen","VW","FSB-9406A","Caja de Cambio"},
			{"Volkswagen","VW","FSBO-8406","Caja de Cambio"},
			{"Volkswagen","VW","FSBO-9406A","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4305 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4305 A/B/C (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4305A (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4305B (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4305C (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4405 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","FSO-4405C","Caja de Cambio"},
			{"Volkswagen","VW","FSO-6406","Caja de Cambio"},
			{"Volkswagen","VW","FSO-6406A","Caja de Cambio"},
			{"Volkswagen","VW","FSO-8406A","Caja de Cambio"},
			{"Volkswagen","VW","MD/RD 23-145","Eje"},
			{"Volkswagen","VW","MICROBUS","Vehículo"},
			{"Volkswagen","VW","MS-19-235 / 23-235 (VW)","Vehículo"},
			{"Volkswagen","VW","MS-23-155 / RS-23-155","Vehículo"},
			{"Volkswagen","VW","MS-23-245","Vehículo"},
			{"Volkswagen","VW","NFB 19320-E","Vehículo"},
			{"Volkswagen","VW","NFB 19340-E","Vehículo"},
			{"Volkswagen","VW","Ônibus 15-180E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 15-190E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 15.180-16.180/210","Vehículo"},
			{"Volkswagen","VW","Ônibus 16-210 Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","ÔNIBUS 16.210/17.240 Motor Tra","Vehículo"},
			{"Volkswagen","VW","ONIBUS 17-210E - Motor Diantei","Vehículo"},
			{"Volkswagen","VW","ONIBUS 17-230E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 17-230E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 17-240 Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 17-240 Motor Trazeiro","Vehículo"},
			{"Volkswagen","VW","ÔNIBUS 17-260 - Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","ONIBUS 17-260E","Vehículo"},
			{"Volkswagen","VW","Ônibus 17.210 OD-17.240 OD/OT","Vehículo"},
			{"Volkswagen","VW","Ônibus 18-310 - Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 18-320 - Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","Ônibus 8.120 OD","Vehículo"},
			{"Volkswagen","VW","Ônibus 8.150","Vehículo"},
			{"Volkswagen","VW","Ônibus 8.150E OD","Vehículo"},
			{"Volkswagen","VW","ONIBUS 9-150 OD","Vehículo"},
			{"Volkswagen","VW","Ônibus Encava E-NT 3200","Vehículo"},
			{"Volkswagen","VW","Ônibus VW 15-180E Motor Tras.","Vehículo"},
			{"Volkswagen","VW","Ônibus VW 16-210","Vehículo"},
			{"Volkswagen","VW","ÔNIBUS VW 17-210","Vehículo"},
			{"Volkswagen","VW","Ônibus VW 17-210 OD Eletrônico","Vehículo"},
			{"Volkswagen","VW","Ônibus VW 17-240 Motor Tras.","Vehículo"},
			{"Volkswagen","VW","Ônibus VW 17-260 OT Eletrônico","Vehículo"},
			{"Volkswagen","VW","Ônibus VW 18-310 - Motor Tras.","Vehículo"},
			{"Volkswagen","VW","RS-19-220 / MS-19-225","Vehículo"},
			{"Volkswagen","VW","RS-19-230 (VW)","Vehículo"},
			{"Volkswagen","VW","RS-23-230","Vehículo"},
			{"Volkswagen","VW","RS-23-240 (VW)","Eje"},
			{"Volkswagen","VW","RT 11710","Caja de Cambio"},
			{"Volkswagen","VW","RT 7608LL","Caja de Cambio"},
			{"Volkswagen","VW","RT 8608LL","Caja de Cambio"},
			{"Volkswagen","VW","RT 8609","Caja de Cambio"},
			{"Volkswagen","VW","RTL 012913","Caja de Cambio"},
			{"Volkswagen","VW","RTL 014918","Caja de Cambio"},
			{"Volkswagen","VW","S5-42","Caja de Cambio"},
			{"Volkswagen","VW","S5-420 (VW)","Caja de Cambio"},
			{"Volkswagen","VW","VW 11-130","Vehículo"},
			{"Volkswagen","VW","VW 11-140","Vehículo"},
			{"Volkswagen","VW","VW 12-140","Vehículo"},
			{"Volkswagen","VW","VW 12-140 H","Vehículo"},
			{"Volkswagen","VW","VW 12-140 T","Vehículo"},
			{"Volkswagen","VW","VW 12-150","Vehículo"},
			{"Volkswagen","VW","VW 12-160","Vehículo"},
			{"Volkswagen","VW","VW 12-170","Vehículo"},
			{"Volkswagen","VW","VW 12-170 BT","Vehículo"},
			{"Volkswagen","VW","VW 12-180","Vehículo"},
			{"Volkswagen","VW","VW 13-130","Vehículo"},
			{"Volkswagen","VW","VW 13-150","Vehículo"},
			{"Volkswagen","VW","VW 13-160","Vehículo"},
			{"Volkswagen","VW","VW 13-170","Vehículo"},
			{"Volkswagen","VW","VW 13-170 E","Vehículo"},
			{"Volkswagen","VW","VW 13-180","Vehículo"},
			{"Volkswagen","VW","vw 13-180E","Vehículo"},
			{"Volkswagen","VW","VW 13-190","Vehículo"},
			{"Volkswagen","VW","VW 13-210","Vehículo"},
			{"Volkswagen","VW","VW 14-140","Vehículo"},
			{"Volkswagen","VW","VW 14-150","Vehículo"},
			{"Volkswagen","VW","VW 14-170 BT","Vehículo"},
			{"Volkswagen","VW","VW 14-180","Vehículo"},
			{"Volkswagen","VW","VW 14-200","Vehículo"},
			{"Volkswagen","VW","VW 14-210","Vehículo"},
			{"Volkswagen","VW","VW 14-220","Vehículo"},
			{"Volkswagen","VW","VW 15-170","Vehículo"},
			{"Volkswagen","VW","VW 15-170 E","Vehículo"},
			{"Volkswagen","VW","VW 15-180","Vehículo"},
			{"Volkswagen","VW","VW 15-180E","Vehículo"},
			{"Volkswagen","VW","VW 15-180E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","VW 15-190","Vehículo"},
			{"Volkswagen","VW","VW 15-190E","Vehículo"},
			{"Volkswagen","VW","VW 15-190E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","VW 16-170","Vehículo"},
			{"Volkswagen","VW","VW 16-170-BT","Vehículo"},
			{"Volkswagen","VW","VW 16-170 BT","Vehículo"},
			{"Volkswagen","VW","VW 16-180","Vehículo"},
			{"Volkswagen","VW","VW 16-200","Vehículo"},
			{"Volkswagen","VW","VW 16-210","Vehículo"},
			{"Volkswagen","VW","VW 16-220","Vehículo"},
			{"Volkswagen","VW","VW 17-210","Vehículo"},
			{"Volkswagen","VW","VW 17-210E","Vehículo"},
			{"Volkswagen","VW","VW 17-210E 2005","Vehículo"},
			{"Volkswagen","VW","VW 17-220","Vehículo"},
			{"Volkswagen","VW","VW 17-230A - MOTOR DIANTEIRO","Vehículo"},
			{"Volkswagen","VW","VW 17-230E","Vehículo"},
			{"Volkswagen","VW","VW 17-230E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","VW 17-240","Caja de Cambio"},
			{"Volkswagen","VW","VW 17-240 (Motor Trazeiro)","Vehículo"},
			{"Volkswagen","VW","VW 17-240 OT","Vehículo"},
			{"Volkswagen","VW","VW 17-240A - MOTOR TRASEIRO","Vehículo"},
			{"Volkswagen","VW","VW 17-250E","Vehículo"},
			{"Volkswagen","VW","VW 17-250LHD","Vehículo"},
			{"Volkswagen","VW","VW 17-260 Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","VW 17-260 OT Eletrônico 2004/","Caja de Cambio"},
			{"Volkswagen","VW","VW 17-260A - MOTOR TRASEIRO","Vehículo"},
			{"Volkswagen","VW","VW 17-260E","Vehículo"},
			{"Volkswagen","VW","VW 17-300/310","Vehículo"},
			{"Volkswagen","VW","VW 17230E","Vehículo"},
			{"Volkswagen","VW","VW 17260 - OT- Eletrônico 2004","Caja de Cambio"},
			{"Volkswagen","VW","VW 17260E","Vehículo"},
			{"Volkswagen","VW","VW 18-310","Vehículo"},
			{"Volkswagen","VW","VW 18-310 Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","VW 18-320 Motor Traseiro","Vehículo"},
			{"Volkswagen","VW","VW 18-320E","Vehículo"},
			{"Volkswagen","VW","VW 18-320E - MOTOR TRASEIRO","Vehículo"},
			{"Volkswagen","VW","VW 18-320E Motor Dianteiro","Vehículo"},
			{"Volkswagen","VW","VW 18320E","Vehículo"},
			{"Volkswagen","VW","VW 19-320","Vehículo"},
			{"Volkswagen","VW","VW 19.310 / 19.320","Vehículo"},
			{"Volkswagen","VW","VW 22-140","Vehículo"},
			{"Volkswagen","VW","VW 22-160","Vehículo"},
			{"Volkswagen","VW","VW 22-210","Vehículo"},
			{"Volkswagen","VW","VW 23-210","Vehículo"},
			{"Volkswagen","VW","VW 23-220","Vehículo"},
			{"Volkswagen","VW","VW 23-220 E","Vehículo"},
			{"Volkswagen","VW","VW 23-250-E","Vehículo"},
			{"Volkswagen","VW","VW 23-250LHD","Vehículo"},
			{"Volkswagen","VW","VW 23.210/220/310(3º eixo 6x2)","Vehículo"},
			{"Volkswagen","VW","VW 24-220","Vehículo"},
			{"Volkswagen","VW","VW 24-220 / 24-250","Vehículo"},
			{"Volkswagen","VW","VW 24-250 E","Vehículo"},
			{"Volkswagen","VW","VW 26-220 / 260","Vehículo"},
			{"Volkswagen","VW","VW 26-220/26-260/26-260E/26-30","Vehículo"},
			{"Volkswagen","VW","VW 26.260/300/310","Vehículo"},
			{"Volkswagen","VW","VW 31-220","Vehículo"},
			{"Volkswagen","VW","VW 31-260 / 31-260E / 31-310 /","Vehículo"},
			{"Volkswagen","VW","VW 31-320","Vehículo"},
			{"Volkswagen","VW","VW 35-300","Vehículo"},
			{"Volkswagen","VW","VW 35-310","Vehículo"},
			{"Volkswagen","VW","VW 40-300","Vehículo"},
			{"Volkswagen","VW","VW 6-140","Vehículo"},
			{"Volkswagen","VW","VW 6-80","Vehículo"},
			{"Volkswagen","VW","VW 6-90","Vehículo"},
			{"Volkswagen","VW","VW 7-100","Vehículo"},
			{"Volkswagen","VW","VW 7-110","Vehículo"},
			{"Volkswagen","VW","VW 7-90","Vehículo"},
			{"Volkswagen","VW","VW 7-91","Vehículo"},
			{"Volkswagen","VW","VW 8-100","Vehículo"},
			{"Volkswagen","VW","VW 8-120","Vehículo"},
			{"Volkswagen","VW","VW 8-120 DELIVERY","Vehículo"},
			{"Volkswagen","VW","VW 8-120 OD","Vehículo"},
			{"Volkswagen","VW","VW 8-140","Vehículo"},
			{"Volkswagen","VW","VW 8-150","Vehículo"},
			{"Volkswagen","VW","VW 8-150 - CO","Vehículo"},
			{"Volkswagen","VW","VW 8-150 DELIVERY","Vehículo"},
			{"Volkswagen","VW","VW 8-150 Eletrônico - Brasil","Vehículo"},
			{"Volkswagen","VW","VW 8-150 OD(VW)","Caja de Cambio"},
			{"Volkswagen","VW","VW 8-150E","Vehículo"},
			{"Volkswagen","VW","VW 8-150E - MÉXICO","Vehículo"},
			{"Volkswagen","VW","VW 8-150E OD","Vehículo"},
			{"Volkswagen","VW","VW 9-150 OD","Vehículo"},
			{"Volkswagen","VW","VW 9-150E","Vehículo"},
			{"Volkswagen","VW","VW 9-90","Vehículo"},
			{"Volkswagen","VW","VW DEDALUS 8 TON - C. DIRETO","Vehículo"},
			{"Volkswagen","VW","VW DEDALUS 8 TON. - C. REMOTO","Vehículo"},
			{"Volvo","VLV","16S-130 (Volvo)","Caja de Cambio"},
			{"Volvo","VLV","16S-1300","Caja de Cambio"},
			{"Volvo","VLV","16S-1300 (VOLVO)","Caja de Cambio"},
			{"Volvo","VLV","16S-160 (Volvo)","Caja de Cambio"},
			{"Volvo","VLV","16S-1600","Vehículo"},
			{"Volvo","VLV","16S-1650 ( Volvo )","Caja de Cambio"},
			{"Volvo","VLV","B-10","Vehículo"},
			{"Volvo","VLV","B-10M","Vehículo"},
			{"Volvo","VLV","B-12","Vehículo"},
			{"Volvo","VLV","B-12 até 1994","Motor"},
			{"Volvo","VLV","B-58","Vehículo"},
			{"Volvo","VLV","B-58E","Vehículo"},
			{"Volvo","VLV","B-7","Vehículo"},
			{"Volvo","VLV","Eixo Traserio Volvo","Eje"},
			{"Volvo","VLV","EV-72","Eje"},
			{"Volvo","VLV","EV-80","Eje"},
			{"Volvo","VLV","EV-81","Eje"},
			{"Volvo","VLV","EV-87","Eje"},
			{"Volvo","VLV","EV-90","Eje"},
			{"Volvo","VLV","EV-91","Eje"},
			{"Volvo","VLV","FH-12","Vehículo"},
			{"Volvo","VLV","FM-10","Vehículo"},
			{"Volvo","VLV","FM-12","Vehículo"},
			{"Volvo","VLV","FS-4205A (VOLVO)","Caja de Cambio"},
			{"Volvo","VLV","FS-5306 (Volvo)","Caja de Cambio"},
			{"Volvo","VLV","FS-6209A (VOLVO)","Caja de Cambio"},
			{"Volvo","VLV","FS-6306 (Volvo)","Caja de Cambio"},
			{"Volvo","VLV","FS-6306A (VOLVO)","Caja de Cambio"},
			{"Volvo","VLV","FSB-5305D (VOLVO)","Caja de Cambio"},
			{"Volvo","VLV","N-10","Vehículo"},
			{"Volvo","VLV","N-12","Vehículo"},
			{"Volvo","VLV","N-12 de 1981 à 1989","Motor"},
			{"Volvo","VLV","NH-12","Vehículo"},
			{"Volvo","VLV","NL-10","Vehículo"},
			{"Volvo","VLV","NL-10 TD 101 FT/FS","Motor"},
			{"Volvo","VLV","NL-12","Vehículo"},
			{"Volvo","VLV","NL-12 até 1995","Motor"},
			{"Volvo","VLV","NL-12 EDC","Vehículo"},
			{"Volvo","VLV","RS-23-240 (Volvo)","Eje"},
			{"Volvo","VLV","S6-80 (Volvo)","Caja de Cambio"},
			{"Volvo","VLV","S6-90 (Volvo)","Caja de Cambio"},
			{"Volvo","VLV","TD 100A - Turbo","Vehículo"},
			{"Volvo","VLV","VM-17 4X2R-210HP","Vehículo"},
			{"Volvo","VLV","VM-17 4x2R 240HP","Caja de Cambio"},
			{"Volvo","VLV","VM-17 4X4R-210HP","Vehículo"},
			{"Volvo","VLV","VM-210 4X2R","Vehículo"},
			{"Volvo","VLV","VM-210 6X2R","Vehículo"},
			{"Volvo","VLV","VM-23 4X2R 210HP","Vehículo"},
			{"Volvo","VLV","VM-23 4x2R 240HP","Caja de Cambio"},
			{"Volvo","VLV","VM-23 6X2R 210HP","Vehículo"},
			{"Volvo","VLV","VM-23 6X2R 240 HP","Vehículo"},
			{"Volvo","VLV","VM-260 4x2R","Caja de Cambio"},
			{"Volvo","VLV","VM-260 6x2R","Caja de Cambio"},
			{"Volvo","VLV","VM 260 4X2R","Caja de Cambio"},
			{"Volvo","VLV","VM 260 6x4R","Vehículo"},
			{"Volvo","VLV","VM17","Vehículo"},
			{"Volvo","VLV","VM23","Vehículo"},
			{"Volvo","VLV","VT 1708B / VT2009B / VT 2514","Caja de Cambio"},
			{"Volvo","VLV","VT 1708B / VT2009B / VT 2514","Eje"},
			{"Volvo","VLV","VT 2014/2214","Caja de Cambio"},
			{"Volvo","VLV","VT 2412B","Vehículo"},
			{"Volvo","VLV","VT 2514","Caja de Cambio"},
			{"Volvo","VLV","VTO 2214B","Vehículo"},
			{"Volvo","VLV","VTO 2514B","Vehículo"}};
	
	static void cargaMarcaModelo() throws Exception{
		
		ArrayList<ArticuloMarcaAplicacion> l = new ArrayList<ArticuloMarcaAplicacion>();
		
		
		String marcaCC = "";
		ArticuloMarcaAplicacion marcaAp = new ArticuloMarcaAplicacion();
		ArticuloModeloAplicacion modeloAp = new ArticuloModeloAplicacion();
		
		
		for (int i = 0; i < modelos.length; i++) {
			String[] dato = modelos[i];
			String marca = dato[0];
			String sigla = dato[1];
			String model = dato[2];
			String tipo  = dato[3];
			if (marca.compareTo(marcaCC) != 0){
				// cambio de marca
				marcaAp = new ArticuloMarcaAplicacion();
				l.add(marcaAp);			
				
				marcaAp.setDescripcion(marca);
				marcaAp.setSigla(sigla);
				
			}
			
			modeloAp = new ArticuloModeloAplicacion();
			modeloAp.setDescripcion(model);
			modeloAp.setTipo(tipo);
			
			marcaAp.getArticuloModeloAplicaciones().add(modeloAp);
			modeloAp.setArticuloMarcaAplicacion(marcaAp);
			
			marcaCC = marca;
			
		}
		
		
		RegisterDomain rr = RegisterDomain.getInstance();
		
		for (int i = 0; i < l.size(); i++) {
			marcaAp = l.get(i);
			System.out.println("marca:"+marcaAp.getDescripcion() + "  -  " + marcaAp.getSigla());
			
			Iterator<ArticuloModeloAplicacion> ite =
			marcaAp.getArticuloModeloAplicaciones().iterator();
			
			while (ite.hasNext()){
				modeloAp = ite.next();
				System.out.println("          "+modeloAp.getDescripcion());
			}
			
			rr.saveObject(marcaAp, "Migra");
		}
		
		
	}
	
	
	
	/**
	 * @param args
	 * @throws Exception 
	 */
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		cargaMarcaModelo();
	}

}
